CREATE TABLE CONTA (
ID		        UNIQUEIDENTIFIER					NOT NULL,
NOME			NVARCHAR(200)						NOT NULL,
DATACRIACAO	    DATE								NOT NULL,
TIPO			NVARCHAR(100)						NOT NULL,
VALOR			DECIMAL(18,2)						NOT NULL,
OBSERVACAO		NVARCHAR(500)						NULL,
CATEGORIA		NVARCHAR(100)						NOT NULL,
PRIMARY KEY(ID))
GO