CREATE TABLE CONTA (
ID				UNIQUEIDENTIFIER					NOT NULL,
NOME			NVARCHAR(200)						NOT NULL,
DATACRIACAO		DATE								NOT NULL,
VALOR			DECIMAL(18,2)						NOT NULL,
OBSERVACAO		NVARCHAR(500)						NOT NULL,
PRIMARY KEY(ID))

GO